In [7]:
import numpy as np
a = np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
import numpy as np

a=np.arange(16).reshape(4,4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
a=np.array([[2,4,5],[1,6,3]])
a

array([[2, 4, 5],
       [1, 6, 3]])

In [21]:
a = np.array([[3,-1,4],[1,5,-9]])
b = np.array([[2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]])
np.dot(a,b)

array([[ 19,  13, -52,   7],
       [-30,  21, 103,  39]])

In [30]:
x = np.array([-3,4,1])
y = np.array([5,2,3])
#x+10
#y*4
#x+y
x*y

array([-15,   8,   3])

In [32]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.filename)

C:\Users\mobd3\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv
